#!/usr/bin/env python3
# Usage:
#   ./bin/version
#       Prints the current version

import os

from packaging.version import parse

ENV_LINODE_CLI_VERSION = "LINODE_CLI_VERSION"


def get_version():
    # We want to override the version if an environment variable is specified.
    # This is useful for certain release and testing pipelines.
    version_str = os.getenv(ENV_LINODE_CLI_VERSION) or "0.0.0"

    return parse(version_str).release


print("{}.{}.{}".format(*get_version()))
