name: WinTest Command

on:
  issue_comment:
    types: [created]

jobs:
  wintest-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: wintest
          named-args: true
          permission: write
