name: Python package

on: [push]

jobs:
  install-dev:
    strategy:
      matrix:
        os: [windows-latest]

    name: Verify dev env
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: "python -m pip install -e .[dev]"
      - run: "python -c 'import structlog; print(structlog.__version__)'"
