name: Run Unit test on windows

on: [push]

jobs:
  unit-tests:
    name: Run unit tests on Windows
    runs-on: windows-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python wheel
        run: pip install wheel boto3

      - name: Update cert
        run: pip install certifi -U

      - name: Install deps
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Install Package
        shell: pwsh
        run: | 
          make install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the unit test suite
        run: make test